### ISSUE TITLE
Not so much an "issue", but smaller buttons possible ?

### ISSUE THREAD

**Issue by aburke20** [falling-fading/legacy-style-ui-upnext-kodi18-plugin#1]
Couldn't find any sort of comment section, so first wanted to thank you so much for this, it is exactly what I was asking the original creator for a week ago, but he never got back to me.

Second, I see that the "buttons/boxes" at the bottom of the pop-up are quite close to each other, and was wondering how I would go about making them just a tad smaller, horizontally ?

Thanks.

**Comment by falling-fading** [comment]
No worries mate! Glad someone else found it useful. 

You'll want to change the width of the button elements. I'll throw links to the lines below. The gaps between the buttons and the button group's alignment will have to be adjusted too - Otherwise your smaller buttons will be offset in the popup. It'll take some adjusting to make everything line up properly. 


#### For the "Up Next" UI:
- Width adjustment:
https://github.com/falling-fading/legacy-style-ui-upnext-kodi18-plugin/blob/master/script-upnext-upnext.xml#L137
  https://github.com/falling-fading/legacy-style-ui-upnext-kodi18-plugin/blob/master/script-upnext-upnext.xml#L148
- Gap between the two buttons:
  https://github.com/falling-fading/legacy-style-ui-upnext-kodi18-plugin/blob/master/script-upnext-upnext.xml#L134
- Alignment of both buttons from the left of the UI:
  https://github.com/falling-fading/legacy-style-ui-upnext-kodi18-plugin/blob/master/script-upnext-upnext.xml#L133


#### For the "Still Watching" IU:
- Width adjustment:
	https://github.com/falling-fading/legacy-style-ui-upnext-kodi18-plugin/blob/master/script-upnext-stillwatching.xml#L137
	https://github.com/falling-fading/legacy-style-ui-upnext-kodi18-plugin/blob/master/script-upnext-stillwatching.xml#L148
- Gap between the two buttons:
	https://github.com/falling-fading/legacy-style-ui-upnext-kodi18-plugin/blob/master/script-upnext-stillwatching.xml#L134
- Alignment of both buttons from the left of the UI:
	https://github.com/falling-fading/legacy-style-ui-upnext-kodi18-plugin/blob/master/script-upnext-stillwatching.xml#L133
